ALTER SEQUENCE passenger_seq INCREMENT BY 1;

ALTER SEQUENCE reservation_seq INCREMENT BY 1;

ALTER SEQUENCE routes_seq INCREMENT BY 1;

ALTER SEQUENCE schedule_seq INCREMENT BY 1;

ALTER SEQUENCE stations_seq INCREMENT BY 1;

ALTER SEQUENCE trains_seq INCREMENT BY 1;

ALTER TABLE passengers
    ALTER COLUMN phone_number DROP NOT NULL;